name: resume_builder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  pdf: ^3.11.1
  open_file: ^3.3.2
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  file_picker: ^8.0.5
  flutter_svg: ^2.0.10+1
  hand_signature: ^3.0.3
  flutter_colorpicker: ^1.1.0
  permission_handler: ^11.3.1
  syncfusion_flutter_pdfviewer: ^24.2.9
  path_provider: ^2.1.4
  firebase_core: ^3.3.0


dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf

    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: OpenSansBoldItalic
      fonts:
        - asset: assets/fonts/OpenSans-BoldItalic.ttf

    - family: OpenSansItalic
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf

    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/preview_layout/


flutter_native_splash:
  image: assets/app_icon.png
  color: "ffffff"
  # fill: true
  
  