name: resume_builder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  pdf: ^3.11.3
  open_file: ^3.5.10
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  file_picker: ^10.1.9
  flutter_svg: ^2.1.0
  hand_signature: ^3.0.3
  flutter_colorpicker: ^1.1.0
  permission_handler: ^12.0.0
  path_provider: ^2.1.5
  firebase_core: ^3.14.0
  syncfusion_flutter_pdfviewer: ^29.1.38


dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  # flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf

    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: OpenSansBoldItalic
      fonts:
        - asset: assets/fonts/OpenSans-BoldItalic.ttf

    - family: OpenSansItalic
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf

    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/preview_layout/


flutter_native_splash:
  image: assets/app_icon.png
  color: "ffffff"
  # fill: true
  
  