// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2zK328LZmdrFhisdpsr-1FBVIc2kegg',
    appId: '1:544270227395:web:56395522491942a09f8f76',
    messagingSenderId: '544270227395',
    projectId: 'resumee-d39fe',
    authDomain: 'resumee-d39fe.firebaseapp.com',
    storageBucket: 'resumee-d39fe.appspot.com',
    measurementId: 'G-J63XVJJTEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi5hAz7lbl_knOChb-V-cXtnQE81hBB6o',
    appId: '1:544270227395:android:601853253c91b76c9f8f76',
    messagingSenderId: '544270227395',
    projectId: 'resumee-d39fe',
    storageBucket: 'resumee-d39fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFCOlFhpt78d6Gz-ySY1OyW868FbDunqk',
    appId: '1:544270227395:ios:80c8a7bfcbba7a0f9f8f76',
    messagingSenderId: '544270227395',
    projectId: 'resumee-d39fe',
    storageBucket: 'resumee-d39fe.appspot.com',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFCOlFhpt78d6Gz-ySY1OyW868FbDunqk',
    appId: '1:544270227395:ios:80c8a7bfcbba7a0f9f8f76',
    messagingSenderId: '544270227395',
    projectId: 'resumee-d39fe',
    storageBucket: 'resumee-d39fe.appspot.com',
    iosBundleId: 'com.example.resumeBuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN2zK328LZmdrFhisdpsr-1FBVIc2kegg',
    appId: '1:544270227395:web:46d7dd7f9f16be819f8f76',
    messagingSenderId: '544270227395',
    projectId: 'resumee-d39fe',
    authDomain: 'resumee-d39fe.firebaseapp.com',
    storageBucket: 'resumee-d39fe.appspot.com',
    measurementId: 'G-XH5J8J7R99',
  );
}
