name: Flutter CI with FVM

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Dart using an official GitHub Action
      - uses: dart-lang/setup-dart@v1

      # Install FVM globally
      - name: Install FVM
        run: dart pub global activate fvm

      # Install the Flutter version defined in the .fvm config
      - name: Install Flutter with FVM
        run: fvm install
        shell: bash

      # Use the installed Flutter version via FVM
      - name: Use Flutter Version with FVM
        run: fvm use
        shell: bash

      # Install Flutter dependencies
      - name: Get Flutter Dependencies
        run: fvm flutter pub get
        shell: bash

      # Run Flutter tests (uncomment if needed)
      # - name: Run Flutter Tests
      #   run: fvm flutter test
      #   shell: bash
      
      # Analyze Dart code
      - name: Analyze Dart Code
        run: fvm dart analyze
        shell: bash

      # Build the Android App Bundle
      - name: Build App Bundle
        run: fvm flutter build appbundle --release
        shell: bash
